using System;
using System.Diagnostics;
using System.IO;
using NUnit.Framework;

namespace TalosAI.Tests
{
    [SetUpFixture]
    public class TestRunner
    {
        [OneTimeSetUp]
        public void BeforeAllTests()
        {
            Directory.CreateDirectory(TestRunSettings.ResultsDirectory);
            // Configure environment to output TRX/JSON if needed by adapters
            Environment.SetEnvironmentVariable("SpecFlow_PluginOutputDir", TestRunSettings.ResultsDirectory);
        }

        [OneTimeTearDown]
        public void AfterAllTests()
        {
            try
            {
                // Generate SpecFlow LivingDoc report if plugin is installed
                // LivingDoc can read feature files and test execution JSON generated by SpecFlow.Plus
                var livingDocExe = Path.Combine(AppContext.BaseDirectory, "livingdoc.exe");
                if (File.Exists(livingDocExe))
                {
                    var psi = new ProcessStartInfo
                    {
                        FileName = livingDocExe,
                        Arguments = $"--output {TestRunSettings.ResultsDirectory} --project {AppContext.BaseDirectory}",
                        UseShellExecute = false,
                        CreateNoWindow = true
                    };
                    using var p = Process.Start(psi);
                    p?.WaitForExit(60000);
                }
            }
            catch { /* ignore report errors */ }
        }
    }
}
